### ISSUE TITLE
CSVkit exercise: convert UFA data fields to OpenTreeMap import template

### ISSUE THREAD

**Issue by rrbaker** [rrbaker/dctreemap#1]
The hosted version of OpenTreeMap has a bulk importer to insert several trees at once via CSV.  As data importers go, it is very particular about the headers and, naturally, these headers do not match up with 

Using [CSVkit](https://csvkit.readthedocs.org/en/0.9.0/#), figure out a series of commands to take [the UFA dataset provided on the DC Gov Open Data portal](http://opendata.dc.gov/datasets/d6364e8d068e4e558c82040569f5d33a_23?geometry=-77.212%2C38.864%2C-76.811%2C38.944) and convert it to the OTM import template (provided in this repository under otm_data).

For now, also removing the UFA fields that do not apply to the standard OTM installation is a plus.

**Comment by emanuelfeld** [comment]
Not sure how many of the fields you want filled upon initial upload. Some of these (esp. street address and any genus/species/cultivar info) will require significant munging. The portal is giving a download error now, but I'd be interested in how much UFA updated since I last standardized the info…

**Comment by emanuelfeld** [comment]
Unless you asked for CSVkit for a reason, this R script should do the trick. https://gist.github.com/emanuelfeld/deb7f2dfbae55f39ad56
